Repository bytedance/UI-TARS-desktop, pull requests merged in 2025-02, with the labels that each got.

#76 fix(permission): macOS permissions updates are not real-time
  .github/workflows/test.yml
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/main/utils/systemPermissions.test.ts
  src/main/utils/systemPermissions.ts
  src/renderer/src/hooks/useDispatch.ts
  src/renderer/src/hooks/usePermissions.ts
  src/renderer/src/hooks/useRunAgent.ts
Labels: bug

#77 feat(share): add screen recording video sharing
  package.json
  packages/action-parser/src/actionParser.ts
  packages/action-parser/test/actionParser.test.ts
  packages/action-parser/test/index.bench.ts
  packages/action-parser/test/index.test.ts
  src/main/main.ts
  src/main/store/ScreenMarker.ts
  src/main/window/index.ts
  src/preload/index.ts
  src/renderer/src/components/ChatInput/index.tsx
  src/renderer/src/components/Header/index.tsx
  src/renderer/src/components/ScreenRecorder/index.tsx
  src/renderer/src/hooks/useScreenRecord.ts
Labels: enhancement

#82 refactor(SoM): setOfMarks Overlays unify into `setOfMarksOverlays` function
  src/main/shared/setOfMarks.test.ts
  src/main/shared/setOfMarks.ts
  src/main/store/runAgent.ts
  src/main/utils/image.ts
  src/main/window/ScreenMarker.ts
  src/main/window/index.ts
  src/renderer/index.html
  src/renderer/src/components/ChatInput/index.tsx
  src/renderer/src/components/RunMessages/index.tsx
  src/renderer/src/hooks/useScreenRecord.ts
  src/renderer/src/hooks/useStore.ts
  tsconfig.web.json
Labels: bug

#94 refactor(ipc-bridge): replace zutron to trpc-like ipc bridge
  package.json
  packages/electron-ipc/README.md
  packages/electron-ipc/package.json
  packages/electron-ipc/src/main/createServer.ts
  packages/electron-ipc/src/main/index.ts
  packages/electron-ipc/src/main/initIpc.ts
  packages/electron-ipc/src/main/registerIpcMain.ts
  packages/electron-ipc/src/renderer/createClient.ts
  packages/electron-ipc/src/renderer/index.ts
  packages/electron-ipc/src/types.ts
  packages/electron-ipc/test/index.test.ts
  packages/electron-ipc/test/test.ts
  packages/electron-ipc/tsconfig.json
  packages/electron-ipc/tsup.config.ts
  packages/electron-ipc/vitest.config.mts
  pnpm-lock.yaml
  src/main/ipcRoutes/agent.ts
  src/main/ipcRoutes/index.ts
  src/main/ipcRoutes/permission.ts
  src/main/ipcRoutes/screen.ts
  src/main/ipcRoutes/window.ts
  src/main/main.ts
  src/main/services/runAgent.ts
  src/main/store/create.ts
  src/main/store/types.ts
  src/main/tray.ts
  src/main/utils/image.ts
  src/main/utils/sanitizeState.ts
  src/main/window/ScreenMarker.ts
  src/main/window/index.ts
  src/preload/index.ts
  src/renderer/index.html
  src/renderer/src/api.ts
  src/renderer/src/components/ChatInput/index.tsx
  src/renderer/src/components/Header/index.tsx
  src/renderer/src/components/RunMessages/index.tsx
  src/renderer/src/hooks/usePermissions.ts
  src/renderer/src/hooks/useRunAgent.ts
  src/renderer/src/hooks/useScreenRecord.ts
  src/renderer/src/hooks/useStore.ts
  src/renderer/src/pages/launcher/index.tsx
  src/renderer/src/pages/settings/index.tsx
  src/renderer/src/typings/preload.d.ts
  src/renderer/src/typings/style.d.ts
  tsconfig.web.json
Labels: v0.0.5

#96 docs: init setting docs
  docs/preset.md
  docs/setting.md
  examples/presets/default.yaml
  images/download-report.png
  images/import-preset-from-local.png
  images/import-preset-from-remote.png
  images/setting.png
  images/upload-report-success.png
  images/utio-flow.png
Labels: v0.0.5

#126 fix(operator): macos cannot type
  src/main/agent/operator.ts
Labels: bug
